apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: monitoring-web-config
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
  labels:
    app.kubernetes.io/part-of: eks-gitops-platform
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: secrets
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster

  template:
    metadata:
      name: 'monitoring-web-config-{{.nameNormalized}}'
      labels:
        app.kubernetes.io/part-of: eks-gitops-platform
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/component: secrets

    spec:
      project: default

      source:
        repoURL: https://github.com/Beem0807/eks-gitops-platform.git
        targetRevision: main
        path: charts/raw
        helm:
          releaseName: monitoring-web-config
          values: |
            resources:
              - apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: prometheus-web-config
                  namespace: monitoring
                spec:
                  refreshInterval: 1h
                  secretStoreRef:
                    name: aws-secrets-manager
                    kind: ClusterSecretStore
                  target:
                    name: prometheus-web-config
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      data:
                        web-config.yaml: |
                          basic_auth_users:
                            {{ "{{" }} .adminUser {{ "}}" }}: "{{ "{{" }} .adminPasswordBcrypt {{ "}}" }}"
                  data:
                    - secretKey: adminUser
                      remoteRef:
                        key: grafana-admin
                        property: adminUser
                        conversionStrategy: Default
                        decodingStrategy: None
                        metadataPolicy: None

                    - secretKey: adminPasswordBcrypt
                      remoteRef:
                        key: grafana-admin
                        property: adminPasswordBcrypt
                        conversionStrategy: Default
                        decodingStrategy: None
                        metadataPolicy: None

              - apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: alertmanager-web-config
                  namespace: monitoring
                spec:
                  refreshInterval: 1h
                  secretStoreRef:
                    name: aws-secrets-manager
                    kind: ClusterSecretStore
                  target:
                    name: alertmanager-web-config
                    creationPolicy: Owner
                    deletionPolicy: Retain
                    template:
                      engineVersion: v2
                      data:
                        web-config.yaml: |
                          basic_auth_users:
                            {{ "{{" }} .adminUser {{ "}}" }}: "{{ "{{" }} .adminPasswordBcrypt {{ "}}" }}"
                  data:
                    - secretKey: adminUser
                      remoteRef:
                        key: grafana-admin
                        property: adminUser
                        conversionStrategy: Default
                        decodingStrategy: None
                        metadataPolicy: None

                    - secretKey: adminPasswordBcrypt
                      remoteRef:
                        key: grafana-admin
                        property: adminPasswordBcrypt
                        conversionStrategy: Default
                        decodingStrategy: None
                        metadataPolicy: None

      destination:
        server: '{{.server}}'
        namespace: monitoring

      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true