apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: prometheus-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    app.kubernetes.io/part-of: eks-gitops-platform
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: monitoring
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'prometheus-crds-{{.nameNormalized}}'
      annotations:
        argocd.argoproj.io/sync-wave: "0"
      labels:
        app.kubernetes.io/part-of: eks-gitops-platform
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/component: monitoring
    spec:
      project: observability
      source:
        repoURL: https://prometheus-community.github.io/helm-charts
        chart: prometheus-operator-crds
        targetRevision: 28.0.1
        helm:
          releaseName: prometheus-crds
      destination:
        server: '{{.server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
          - ClientSideApplyMigration=false