apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: grafana-admin-secret
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
  labels:
    app.kubernetes.io/part-of: eks-gitops-platform
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: secrets
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'grafana-admin-secret-{{.nameNormalized}}'
      labels:
        app.kubernetes.io/part-of: eks-gitops-platform
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/component: secrets
    spec:
      project: observability
      source:
        repoURL: https://github.com/Beem0807/eks-gitops-platform.git
        targetRevision: main
        path: charts/raw
        helm:
          releaseName: grafana-admin-secret
          values: |
            resources:
              - apiVersion: external-secrets.io/v1beta1
                kind: ExternalSecret
                metadata:
                  name: grafana-admin
                  namespace: monitoring
                spec:
                  refreshInterval: 1h
                  secretStoreRef:
                    name: aws-secrets-manager
                    kind: ClusterSecretStore
                  target:
                    name: grafana-admin
                    creationPolicy: Owner
                  data:
                    - secretKey: admin-user
                      remoteRef:
                        key: grafana-admin
                        property: adminUser
                        conversionStrategy: Default
                        decodingStrategy: None
                        metadataPolicy: None

                    - secretKey: admin-password
                      remoteRef:
                        key: grafana-admin
                        property: adminPassword
                        conversionStrategy: Default
                        decodingStrategy: None
                        metadataPolicy: None
      destination:
        server: '{{.server}}'
        namespace: monitoring
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
