apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: reloader
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
  labels:
    app.kubernetes.io/part-of: eks-gitops-platform
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: secrets
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters:
        selector:
          matchLabels:
            argocd.argoproj.io/secret-type: cluster
  template:
    metadata:
      name: 'reloader-{{.nameNormalized}}'
      labels:
        app.kubernetes.io/part-of: eks-gitops-platform
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/component: secrets
    spec:
      project: platform
      source:
        repoURL: https://stakater.github.io/stakater-charts
        chart: reloader
        targetRevision: 1.1.0
        helm:
          releaseName: reloader
          values: |
            reloader:
              watchGlobally: true

              deployment:
                nodeSelector:
                  app: core

                tolerations:
                  - key: app
                    operator: Equal
                    value: core
                    effect: NoSchedule
      destination:
        server: '{{.server}}'
        namespace: reloader
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - ServerSideApply=true
      ignoreDifferences:
        - group: apps
          kind: Deployment
          name: reloader-reloader
          namespace: reloader
          jqPathExpressions:
            - .spec.template.spec.containers[].env[]?.valueFrom.resourceFieldRef.divisor