apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-time-service
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: simple-time-service-{{.nameNormalized}}
    spec:
      project: default
      source:
        repoURL: https://github.com/Beem0807/eks-gitops-platform.git
        targetRevision: main
        path: charts/simple-time-service
        helm:
          values: |
            image:
              tag: latest
            serviceMonitor:
              enabled: true
      destination:
        server: '{{.server}}'
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true