apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: simple-time-service
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: eks-gitops-platform
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/component: workload
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - clusters: {}
  template:
    metadata:
      name: simple-time-service-{{.nameNormalized}}
      labels:
        app.kubernetes.io/part-of: eks-gitops-platform
        app.kubernetes.io/managed-by: argocd
        app.kubernetes.io/component: workload
    spec:
      project: default
      source:
        repoURL: https://github.com/Beem0807/eks-gitops-platform.git
        targetRevision: main
        path: charts/simple-time-service
        helm:
          values: |
            image:
              tag: latest
            serviceMonitor:
              enabled: true
            hpa:
              enabled: true
            networkPolicy:
              enabled: false
      destination:
        server: '{{.server}}'
        namespace: simple-time-service
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true